# https://cwiki.apache.org/confluence/display/INFRA/.asf.yaml+features+for+git+repositories

github:
  description: "Build highly concurrent, distributed, and resilient message-driven applications using Java/Scala"
  homepage: https://pekko.apache.org/
  labels:
    - pekko
    - streaming
    - reactive
    - actor-model
    - concurrency
    - cloud-native
    - distributed-actors
    - distributed-systems
    - high-performance
  
  features:
    # Enable wiki for documentation
    wiki: false
    # Enable issue management
    issues: true
    # Enable projects for project management boards
    projects: false

  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  true

notifications:
  commits:              commits@pekko.apache.org
  issues:               notifications@pekko.apache.org
  pullrequests:         notifications@pekko.apache.org
  discussions:          notifications@pekko.apache.org

